### ISSUE TITLE
Deprecated Exercises (As Not Logged in User)

### ISSUE THREAD

**Issue by butuzov** [exercism/go#1164] opened 2018-09-17 20:30 UTC
I was parsing tracks page (  https://exercism.io/tracks/go/exercises ) as non-logged in user, and notice that there are few tracks not on their places

All of the listed tracks are appears at the bottom of the track list page (so its easy to notice).

### Deprecated  (All your base)
Next exercises are looks like a previous version of the "All your base"

 - Hexadecimal
 - Binary
 - Octal
 - Trinary

### Deprecated 
- Counter

Is `deprecated` property (of each exercise) just ignored intentionally or it's a bug?

**Comment by hilary** [comment] 2018-09-17 22:31
Could you provide a screenshot? I'm not sure what you are saying.

**Comment by butuzov** [comment] 2018-09-18 04:42
Way to reproduce/see this.

1. Open Chrome in Incognito mode
2. Open URL https://exercism.io/tracks/go/exercises
3. Scroll down and check last five exercises.
![image](https://user-images.githubusercontent.com/651824/45664454-8b8fd780-bb14-11e8-8a7f-3dc47dd0968f.png)

They are **not** available if you are logged in practice mode. 
![image](https://user-images.githubusercontent.com/651824/45664528-efb29b80-bb14-11e8-96f2-9954cdb3abc5.png)

In `config.json` all of them has key entry `deprecerated`. 

P.S.
You also can also do `exercism download --exercise=counter --track=go` , but I am not sure  this action if forbiden.

P.P.S.
Sorry for huge screen.

**Comment by hilary** [comment] 2018-09-18 19:06
Interesting! I'm not sure, but I think it's a bug. Checking...

**Comment by hilary** [comment] 2018-09-18 19:19
Ok, looked into it, and, while it may be disconcerting, it is not a bug. If you click on an exercise from that view, you are taken to the community solutions for the exercise. 

I believe that the idea was that we would still show community solutions for deprecated exercises. 

I'm not sure that still applies, though...

**Comment by hilary** [comment] 2018-09-18 19:33
I'm raising the issue more generally in exercism/issues and closing it in this track. See also https://github.com/exercism/exercism/issues/4360

**Closed by hilary** 2018-09-18 19:33 UTC
